name: 2-Extract and Save Fund Holdings and Analysis

# -----------------------------------------------------------
# 修改点 1: 限制触发条件 - 只有指定文件改动时才运行
# -----------------------------------------------------------
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/integrated_fund_screener.yml'
      - 'integrated_fund_screener.py'
  
  # -----------------------------------------------------------
  # 修改点 2: 设置定时运行 - 每 3 小时运行一次
  # -----------------------------------------------------------
  schedule:
    # '0 */3 * * *' 表示每隔 3 小时的第 0 分钟运行一次 (如 00:00, 03:00, 06:00 等)
    - cron: '0 */3 * * *'
  
  workflow_dispatch:

jobs:
  extract-data:
    # -----------------------------------------------------------
    # 修改点 3: 设置时区环境变量为 Asia/Shanghai (上海时间)
    # -----------------------------------------------------------
    env:
      TZ: Asia/Shanghai
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # *** 关键修改：确保 akshare 等所有必需的库都被安装 ***
          pip install pandas requests beautifulsoup4 numpy akshare

      - name: Run fund screening script
        # 运行您核心的筛选脚本
        run: python integrated_fund_screener.py

      - name: Commit and push the new data and analysis files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 定义所有需要跟踪的文件，包含新生成的日志和失败文件
          files=(
            "fund_holdings.json"
            "fund_analysis.json"
            "fund_basic_info.xlsx"
            "fund_basic_info.csv"
            "all_fund_codes.csv"
            "risk_metrics.json"
            "fund_managers_data/fund_managers_*.json"
            "fund_codes.csv"
            "fund_rankings.csv"
            "selected_funds.csv"
            "valuation_*.json"
            "manager_index_screened_funds.csv"
            "recommended_cn_funds.csv"
            "filtered_funds.csv"
            "merged_funds.csv"
            "fund_screener.log"
            "failed_funds.txt"
            "fund_screener_optimized_result_*.xlsx" # <<< 关键新增：匹配新脚本的输出文件
          )
          
          # <<< 关键新增：添加 fund_data 目录中的所有 CSV 缓存文件
          find fund_data -name "*.csv" -print0 | xargs -0 git add || true
          
          # 添加所有列出的文件
          for file in "${files[@]}"; do
            if ls $file 2>/dev/null; then
              git add $file
            else
              echo "未找到 $file"
            fi
          done
          
          # 检查是否有文件被添加或修改
          if git diff-index --quiet HEAD --; then
            echo "没有文件更改，跳过提交。"
          else
            git commit -m "Automated: Update fund data and analysis results (including local cache)"
            git push
          fi
